### PR TITLE
chore(package): update dependencies

### PR DESCRIPTION
**Pull request by falsandtru**
@twada I found the failed test in Node 0.12. Can you take a look?

https://travis-ci.org/twada/power-assert-keeper/builds/173166803

### CODE REVIEW

**Comment by twada** [comment]
@falsandtru Okay I'll take a look.
(I'm a bit busy now so maybe in this weekend.)

**Comment by falsandtru** [comment]
Thanks. Note: Node version is implicitly changed from v0.12.14 to v0.12.17.

**Comment by falsandtru** [comment]
@twada As a notice, I enabled the cron feature of travis. So if we could recover this failure, this repo would work more.

**Comment by twada** [comment]
@falsandtru Thanks. I've made a local repro case and now tackling with this issue. A bit wired case...

**Comment by twada** [comment]
Just created a reproduction case repository and PR for the fix. Will land and release today or tomorrow.

[twada/power-assert-deep-strict-equal-reference-error-repro: power-assert 1.4.1 under Node v0.12.x and Babel6 bug reproduction](https://github.com/twada/power-assert-deep-strict-equal-reference-error-repro)

[Fix deepStrictEqual usage to run with old Node (v0.12) by twada · Pull Request #71 · power-assert-js/power-assert](https://github.com/power-assert-js/power-assert/pull/71)

**Comment by falsandtru** [comment]
Thanks!

**Pull request merged**
